version: '3'
services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - PORT=${PORT}
    ports:
      - 3000:3000